name: GitHub Readme Snake
on:
  schedule:
    - cron: '0 0 * * *'  # runs daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Snake
        uses: platane/snk@v1.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: 'github-contribution-grid-snake.svg'
      - name: Commit Snake
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add github-contribution-grid-snake.svg
          git commit -m "Update snake graph" || echo "No changes to commit"
          git push

